# Generated by Django 5.2 on 2025-05-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestresponse",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="response_images"),
        ),
        migrations.AddField(
            model_name="searchrequest",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="search_requests"),
        ),
    ]
